RecruTask/Models/ErrorViewModel.cs
namespace RecruTask.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

RecruTask/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RecruTask.Models;

namespace RecruTask.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

RecruTask/Controllers/RecruTaskController.cs
using Microsoft.AspNetCore.Mvc;
using RecruTask.Services;

namespace RecruTask.Controllers;

public class RecruTaskController : Controller
{
    private readonly IRecruTaskService _recruTaskService;

    public RecruTaskController(IRecruTaskService recruTaskService)
    {
        _recruTaskService = recruTaskService;
    }

    public ActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public ActionResult ProcessArray(string inputArray)
    {
        int[] parsedArray;

        try
        {
            parsedArray = PrepareArray(inputArray.Replace(" ", string.Empty));
        }
        catch (Exception e)
        {
            return View("Index", (inputArray, e.Message));
        }
        
        return View("Index", (inputArray, $"[{string.Join(',', _recruTaskService.FindIfItemsInArrayRepeatAtLeastThreeTimes(parsedArray.ToArray()))}]"));
    }

    
    //can be also moved to another class, but we don't have a lot of code there so no worth to refactor that.
    //Also integration tests would be nice there, to test more theory cases.
    private static int[] PrepareArray(string inputArray)
    {
        if (inputArray.FirstOrDefault() == '[' && inputArray.Last() == ']')
        {
            inputArray = inputArray.Substring(1, inputArray.Length - 2);
        }
        else if (inputArray.Length == 0)
        {
            return Array.Empty<int>();
        }
        else
        {
            //in production soft i would use more specified exceptions, and more specified Exception handling
            throw new Exception("not valid format. You should put array in []");
        }
        var result = inputArray.Split(',');
        var parsedResult = new List<int>();
        try
        {
            foreach (var element in result)
            {
                var parsed = int.Parse(element);
                parsedResult.Add(parsed);
            }
        }
        catch (Exception)
        {
            throw new Exception("error while processing");
        }


        return parsedResult.ToArray();
    }
}

RecruTask/Views/RecruTask/Index.cshtml
@model (string inputArray, string output)

@{
    ViewBag.Title = "Array Input Page";
}

<h2>Enter an Integer Array</h2>

@using (Html.BeginForm("ProcessArray", "RecruTask", FormMethod.Post))
{
    <div>
        @Html.Label("inputArray", "Enter an integer array:")
        @Html.TextBox("inputArray", Model.inputArray, new { value="[]", placeholder = "[x,y,z]", size = 30 })
    </div>
    <div>
        <input type="submit" value="Process" />
    </div>
}

@if (!string.IsNullOrEmpty(Model.inputArray))
{
    <h3>Entered Array:</h3>
    <p>@Model.inputArray</p>
    <h3>Result:</h3>
    <p>@Model.output</p>
    <p></p>
}

RecruTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RecruTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RecruTask.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">

</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>